# Generated by Django 4.1 on 2023-01-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('img', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('notes', models.CharField(max_length=256)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page_app.car')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_end_date', to='landing_page_app.date')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_start_date', to='landing_page_app.date')),
            ],
        ),
    ]
