# Generated by Django 4.1 on 2023-01-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
